version: '3.8'

services:
  backend:
    container_name: tech_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: ./do run
    volumes:
      - ./:/app
    ports:
      - "8025:8025"
    depends_on:
      - postgres
    networks:
      - proxy_net

  postgres:
    container_name: tech_postgres
    image: postgres:13
    environment:
      POSTGRES_USER: tech
      POSTGRES_PASSWORD: tech
      POSTGRES_DB: tech
    ports:
      - "5432:5432"
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: tech_proxy_net
